### ISSUE TITLE
Spaces sometimes inserted two characters after underscore in label 

### ISSUE THREAD

**Issue by mephph** [nschloe/blacktex#11]
A small working example:

```tex
\documentclass{standalone}
\begin{document}
\section{One} \label{one_one}
\section{Two} \label{_two}
\section{Three} \label{three_t}
\subsection{Four} \label{__}
\end{document}
```
blacktex produces the following:

```tex
\documentclass{standalone}
\begin{document}
\section{One}\label{one_o ne}
\section{Two}\label{_t wo}
\section{Three}\label{three_t}
\subsection{Four}\label{__}
\end{document}
```

Notice that the first two labels are changed while the last two are not.

The output of `blacktex -v` is `blacktex 0.2.1, Python 3.8.2`.

**Comment by nschloe** [comment]
Not sure if blacktex will ever deal with this. Underscores are assumed to occur in math mode, and there, `one_o ne`  is actually better (because only the first `o` is put in the subindex). Of course, this should really only happen in _math mode_, but for this, blacktex would have to include an actual parser, which it probably never will.

**Comment by mephph** [comment]
Underscores are useful in labels and bibliography entry names. As one example, the wonderful package cleveref doesn't accept spaces in references (without significant hacking). This modification of labels makes blacktex unusable for me and many LaTeX users whose code I've seen.

You are correct that it is impossible to detect math mode without parsing. It should be much easier to detect an enclosing command like \label, \cite, \cref, \ref, or \eqref.

**Comment by nschloe** [comment]
PRs welcome!
